apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  HTTP_PORT: "8080"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT: "http://localstack-svc:4566"
  SNS_TOPIC_CATALOG_EVENTS_ARN: "arn:aws:sns:us-east-1:000000000000:catalog-events-topic"
  SQS_ORDERS_APPROVED_QUEUE_URL: "http://sqs.us-east-1.localstack-svc:4566/000000000000/orders-approved-queue"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@catalog-postgres-svc:5432/catalog_db?sslmode=disable"
  JWT_SECRET: "local-dev-secret"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
