apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-postgres
  template:
    metadata:
      labels:
        app: catalog-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: catalog_db
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-postgres-svc
spec:
  selector:
    app: catalog-postgres
  ports:
    - port: 5432
      targetPort: 5432
